title: Trusted Firmware
email: board@trustedfirmware.org
description: >- # this means to ignore newlines until "baseurl:"
  Arm’s Trusted Firmware is adopting Open Governance and is now and Open Source project managed by Linaro.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.trustedfirmware.org" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
markdown: kramdown
theme: jumbo-jekyll-theme
plugins:
  - jekyll-data
exclude:
    - .asset-cache
    - .sass-cache
    - _site
    
permalink: /blog/:title/

collections:
    authors:
        output: true
        permalink: /author/:name/
# Jekyll Assets plugin - set js and css to true so it compresses on jekyll build
assets:
  compress:
        js: true
  autoprefixer:
      browsers: ["last 2 versions","> 5%","IE 9"]
  sources:
    - assets/js/
    - assets/js/vendor/
    - assets/js/app/
    - assets/images
    - assets/images/authors
    - assets/css/
    - assets/css/app

defaults:
  - scope:
        path: ""
        type: "authors"
    values:
        layout: author