title: Trusted Firmware

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://staging.trustedfirmware.org" # the base hostname & protocol for your site, e.g. http://example.com
destination: staging.trustedfirmware.org
production: false

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
 
